#ifndef HEADER
#define HEADER
#define KEYWORD 10
#define IDENTIFIER 11
#define INTEGER_CONSTANT 12
#define FLOATING_CONSTANT 13
#define ENUMERATION_CONSTANT 14
#define CHARACTER_CONSTANT 15
#define STRING_LITERAL 16
#define PUNCTUATOR 17
#define SINGLE_LINE_COMMENT 18
#define MULTI_LINE_COMMENT 19
#define WHITESPACE 20
#define LINEFEED 21
#define UNKNOWN 22
#endif